require("dotenv").config();
const express = require("express");
const cors = require("cors");
const helmet = require("helmet");
const morgan = require("morgan");
const rateLimit = require("express-rate-limit");
const { connectDB } = require("./db");
const { sanitizeBody } = require("./middleware/sanitize");
const { UPLOAD_DIR } = require("./middleware/upload");
const { taskSyncGuard } = require("./middleware/syncGuard");
const { deleteReplay } = require("./middleware/deleteReplay");
const authRoutes = require("./routes/auth");
const userRoutes = require("./routes/users");
const taskRoutes = require("./routes/tasks");
const noteRoutes = require("./routes/notes");
const reminderRoutes = require("./routes/reminders");
const eventRoutes = require("./routes/events");
const assistantRoutes = require("./routes/assistant");
const pushRoutes = require("./routes/push");
const billingRoutes = require("./routes/billing");
const organizationRoutes = require("./routes/organization");
const auditRoutes = require("./routes/audit");
const { stripeWebhookHandler } = require("./routes/billingWebhook");
const { startDailyDigestJob } = require("./jobs/dailyDigest");
const app = express();
app.set("trust proxy", 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
const allowedOrigins = (process.env.CORS_ORIGIN || "").split(",").map((s) => s.trim()).filter(Boolean);
app.use(cors({ origin: allowedOrigins.length ? allowedOrigins : true, credentials: true }));
if (process.env.NODE_ENV !== "test") app.use(morgan("tiny"));
app.post("/api/billing/webhook", express.raw({ type: "application/json" }), stripeWebhookHandler);
app.use(express.json({ limit: "1mb" }));
app.use(sanitizeBody);
app.use("/uploads", express.static(UPLOAD_DIR, { maxAge: "7d" }));
const authLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 30, standardHeaders: true, legacyHeaders: false });
app.use("/api/auth", authLimiter);
const apiLimiter = rateLimit({ windowMs: 15 * 60 * 1000, max: 600, standardHeaders: true, legacyHeaders: false });
app.use("/api", apiLimiter);
app.get("/api/health", (req, res) => res.json({ ok: true }));
app.use("/api/auth", authRoutes);
app.use("/api/users", userRoutes);
app.use("/api/tasks", taskSyncGuard, taskRoutes);
app.use("/api/notes", deleteReplay, noteRoutes);
app.use("/api/reminders", deleteReplay, reminderRoutes);
app.use("/api/events", deleteReplay, eventRoutes);
app.use("/api/assistant", assistantRoutes);
app.use("/api/push", pushRoutes);
app.use("/api/billing", billingRoutes);
app.use("/api/organization", organizationRoutes);
app.use("/api/audit", auditRoutes);
app.use("/api", (req, res) => res.status(404).json({ error: "Not found" }));
app.use((err, req, res, next) => { if (err && err.name === "MulterError") return res.status(400).json({ error: err.code === "LIMIT_FILE_SIZE" ? "File is too large" : err.message }); if (err && err.name === "ValidationError") return res.status(400).json({ error: Object.values(err.errors).map((e) => e.message).join("; ") }); if (err && err.name === "CastError") return res.status(400).json({ error: "Invalid ID format" }); if (err && err.code === 11000) return res.status(409).json({ error: "That value is already in use" }); console.error(err); res.status(err.status || 500).json({ error: err.message || "Something went wrong" }); });
const PORT = process.env.PORT || 4000;
connectDB().then(() => { app.listen(PORT, () => console.log(`Noote API listening on port ${PORT}`)); startDailyDigestJob(); }).catch((err) => { console.error("Failed to start server:", err.message); process.exit(1); });
